version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - 6389:6379

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    networks:
      - db-net
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    networks:
      - db-net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: admin

networks:
  db-net:

volumes:
  db-data:
